### ISSUE TITLE
'huser' values in oni-ingest vs oni-setup

### ISSUE THREAD

**Issue by EverLoSa** [Open-Network-Insight/open-network-insight#11]
Hello,
I observed a mis match of the variable 'huser's value in ingest component and oni-setup scripts.

Value in duxbay.conf configuration file: '/user/duxbury'
Refer: https://github.com/Open-Network-Insight/oni-setup/blob/master/duxbay.conf#L9

Value in oni-ingest's master_ingest configuration file is '/user/oni'
Refer: https://github.com/Open-Network-Insight/oni-ingest/blob/master/ingest/etc/master_ingest.json#L13

Due to this configuration, all nfcapd binaries are being ingested under hfds location '/user/oni' but the ML component is looking for data under '/user/duxbury' for pre processing. To bring back things to nornal, we had to move older repo versions for Ingest and ML components. Please let me know if my writeup doesn't make sense or if I am missing anything here.

Sai Ganji Cloudwick

**Comment by NathanSegerlind** [comment]
I am addressing this in a fork so I can get working on some things...  if you got a branch/fork, I call it in or if you'd rather, you can pull my fork to get this fixed

cheers,
the nate

**Comment by natedogs911** [comment]
This is an old issue, has been resolved. all users now 'spot'
