### ISSUE TITLE
ML feedback is not working for flows

### ISSUE THREAD

**Issue by EverLoSa** [Open-Network-Insight/open-network-insight#13]

**Comment by grantbabb** [comment]
Worst issue creation, ever.  

The issue communicated over Slack was that the logic to read in feedback files did not appear to be in the code in the dev branch.  

Will add a branch and create a pull request immediately to resolve.   Recommend following hotfix process.

I will create a separate issue for "automated loading of feedback file".  Will add oni-oa label to that issue.

**Comment by grantbabb** [comment]
fix submitted in oni-ml PR#4

**Comment by NathanSegerlind** [comment]
Ever - is this fixed and can we close the issue?

**Comment by NathanSegerlind** [comment]
Per discussion in today's Pull Request meeting, I am taking over this issue and will open a new pull request for it.

**Comment by natedogs911** [comment]
closed in pull request Open-Network-Insight/oni-ml#4
