### ISSUE TITLE
wiki: Validate ingest

### ISSUE THREAD

**Issue by NathanSegerlind** [Open-Network-Insight/open-network-insight#15]
https://github.com/Open-Network-Insight/oni-docs/wiki/Validate%20ingest

CONCERN 1

The "validate that tshark is properly installed" step uses a capital V option for the version.... version information for tshark is obtained with the the lower-case v option

that is

"tshark -V" should be changed to "tshark -v"

Otherwise you get a cryptic failure message, per:

[oni@sec-cdh16 ~]$ tshark -V
tshark: There are no interfaces on which a capture can be done

[oni@sec-cdh16 ~]$ tshark -v
TShark (Wireshark) 2.0.1 (SVN Rev Unknown from unknown)

Copyright 1998-2015 Gerald Combs <gerald@wireshark.org> and contributors.
License GPLv2+: GNU GPL version 2 or later <http://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Compiled (64-bit) with libpcap, without POSIX capabilities, without libnl, with
libz 1.2.3, with GLib 2.28.8, without SMI, without c-ares, without ADNS, without
Lua, without GnuTLS, with Gcrypt 1.4.5, with MIT Kerberos, without GeoIP.

Running on Linux 2.6.32-431.el6.x86_64, with locale en_US.UTF-8, with libpcap
version 1.4.0, with libz 1.2.3, with Gcrypt 1.4.5.
Intel(R) Xeon(R) CPU E5-2699 v3 @ 2.30GHz (with SSE4.2)

Built using gcc 4.4.7 20120313 (Red Hat 4.4.7-16).

CONCERN 2 

instructions to start the ingest framework and validate that is is running are somewhat cryptic --- the user is not told how to properly substitute for "ingest type" or "%H_%M_%S"

a worked example with actual values would be better

CONCERN 3

there are no instructions for how to turn off the ingest process after it has been validated...

**Comment by natedogs911** [comment]
1. fixed the tshark validation step
2. added more context around screen
3. added closing instructions for screen
@NathanSegerlind
