### ISSUE TITLE
User domain is currently hard coded as "intel"

### ISSUE THREAD

**Issue by brandon-edwards** [Open-Network-Insight/open-network-insight#158]
On line 67 of  [https://github.com/Open-Network-Insight/open-network-insight/blob/spot/spot-ml/src/main/scala/org/apache/spot/utilities/DomainProcessor.scala](url) the code tests the domain string variable against the string "intel" in order to determine whether the domain should be considered to be in the users domain. For non intel solution-users this is a problem.

**Comment by dataminion** [comment]
I don't think this is a bug, the files that specifically list intel as the domain are Tests, from that perspective perhaps there needs to be a test that validates a domain not intel. I suggest it should be re-labeled as an enhancement. @natedogs911 thoughts?

**Comment by brandon-edwards** [comment]
@dataminion I should have closed the issue, we recently merged code (into THIS repo) to resolve it. As for the tests, we are in the process of increasing test coverage. However, the repeated occurrences of the userDomain value "intel" appear in tests for which the value of userDomain does not play the main role.
