### ISSUE TITLE
wiki: Install ML prerequisites

### ISSUE THREAD

**Issue by NathanSegerlind** [Open-Network-Insight/open-network-insight#16]
https://github.com/Open-Network-Insight/oni-docs/wiki/Install%20ML%20Prerequisites

It is not clear from this documentation if mpich is supposed to be pushed to all of the worker nodes and installed, nor is it said how to install mpich on said worker nodes.

**Comment by saiganji** [comment]
To add more this, the instructions for machine_file in lda_c are not complete. For ML pipeline to work fine, the first host in machine_file should the ml master node.

**Comment by rabarona** [comment]
One more thing we discovered last night was that installing ONI on Centos 7.0 which comes with python 2.7.5 already will require to manually install numpy for scripts lda_pre.py and lda_pos.py to run.

I haven't found specific documentation for this but installations on systems with python 2.6 won't require this step, seems to be already installed. 

@NathanSegerlind shall we break these issues into multiple git issues? Something like 
wiki: Install ML prerequisites <prerequisite>

Thanks.

**Comment by NathanSegerlind** [comment]
added link to install NumPy

**Comment by NathanSegerlind** [comment]
added note that MLNODE is the first node on the list NODES

**Comment by NathanSegerlind** [comment]
edited page on installing MPI runtime engine on nodes of NODES for clarity
