### ISSUE TITLE
hdfs_setup.sh should be executed as hdfs user

### ISSUE THREAD

**Issue by kpeiruza** [Open-Network-Insight/open-network-insight#178]
Otherwise the script fails.

Just add a comment on the setup instructions or modify the script to check whether hadoop hdfs -mkdir ${HUSER} worked.

I'd suggest to check if source /etc/spot.conf worked as well, as the setup will do weird things if it doesn't exist.

PS: if Sentry is enabled, then creating the Hive tables will be restricted to a subset of users, so I'd suggest making it mandatory to run it under "hdfs" user or exit.

**Comment by kpeiruza** [comment]
PS: the 1st chown on the script isn't propagated, so, after creating all subfolders a chown should be executed or the script should be executed as spot but the home creation should be done with hdfs...

**Comment by EverLoSa** [comment]
Hi @kpeiruza ,

We migrated to ASF, can you please move this issue to our Jira: 
https://issues.apache.org/jira/issues/?jql=project%20%3D%20SPOT

Regards,
Ever

**Comment by natedogs911** [comment]
@kpeiruza i'll watch for the jira issue, my experience is that if you run as `hdfs` the script will break when kerberos is enabled. I agree we need some error checking and additional info in the script. perhaps we can work that out in the comments on the jira and come up with a PR
