### ISSUE TITLE
Syslogs Use case

### ISSUE THREAD

**Issue by chrameshraj** [Open-Network-Insight/open-network-insight#179]
Hi all,

I’m a Bigdata Consultant and I’d like some guidance, Are there any deployment examples of the Apache Spot solution, in small-scale testebeds at all?

As I’m trying to test Apache Spot on a testbed, consisting of a small hadoop cluster (3-5 clients ). I would like to ingest all of my cluster the syslogs & the network flow to the edge node (ingest), followed by ML and OA procedures, as described in the documentation, in order to monitor the events activity.

What I’m concerned about can we have real time threat dection on our hadoop nodes syslog events ingested to the  hadoop cluster using (Flume+Kafka) to hdfs+hive/hbase. Is it possible to create “hooks” to each type of suspicious activity that will trigger custom counter measures or alerts ? To archive this use case what are the minimal step requirements ?  

Any help would be appreciated! 

Thank you for your time.

Ramesh

**Comment by natedogs911** [comment]
Hello,
Currently the solution is running ML in batches. Realtime detection is certainly in the roadmap but not in the solution yet. We have done some work with triggering changes to firewalls through the OSC, I think this will be better facilitated with the new API however this still requires someone to trigger these changes.

As a sidenote. Although the issues section has been been closed please use the new [Apache Spot Jira](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=0ahUKEwiC7Nyn8djSAhVB6WMKHStkD6EQFggcMAA&url=https%3A%2F%2Fissues.apache.org%2Fjira%2Fbrowse%2FSPOT&usg=AFQjCNG8e73NmtbpHHhDZqZhz1FNGrFD3w&sig2=YUiDINuXa6YRl5Z-bzox8A)
I would suggest proposing your workflow in an issue there for discussion.
I have some ideas related to your question that we could discuss as a community.
Thank you for your time,
- nathanael
