### ISSUE TITLE
Need test data

### ISSUE THREAD

**Issue by Manjesh80** [Open-Network-Insight/open-network-insight#180]
Hi Folks, I'm testing the "PROXY" flow, and I was able to setup the pipeline in Cloudera VM

Can you folks help me with some sample proxy log files , even if its 10 lines its fine. The data I prepared is bit messed up.

**Comment by vgonzale78** [comment]
you can download a sample from the following location
https://s3-us-west-2.amazonaws.com/apachespot/public_data_sets/proxy_aws/Bluecoat_ProxySG_Sample

**Comment by Manjesh80** [comment]
thanks for the reply and data
