### ISSUE TITLE
HUSER setting in hiveconf create_*_avro.sql

### ISSUE THREAD

**Issue by grantbabb** [Open-Network-Insight/open-network-insight#23]
In the setup scripts,
${hiveconf:huser} will be /user/soluser
and so '/user/${hiveconf:huser}/dns/hive' will be '/user/user/soluser/dns/hive'
This makes a bug and cannot create hive tables.
LOCATION '/user/${hiveconf:huser}/dns/hive'

**Comment by grantbabb** [comment]
originally opened by @pkuwm

**Comment by natedogs911** [comment]
fixed in PR Open-Network-Insight/oni-setup#6
