### ISSUE TITLE
Flows Edge Investigation Notebook is not executing correctly

### ISSUE THREAD

**Issue by LedaLima** [Open-Network-Insight/open-network-insight#24]
The order of the cells is not  allowing the correct execution of the notebook at first attempt. It's trying to execute functions that haven't been defined yet.

**Workaround:**  Locate and execute first the cell under the "Initialize Workflow" title.
After that, you can click on "Cell" > "Run all" and the notebook will be correctly initialized

**Comment by EverLoSa** [comment]
PR: https://github.com/Open-Network-Insight/oni-oa/pull/24

Fixed in 1.0.1
