### ISSUE TITLE
Pre_lda.py skipping first line

### ISSUE THREAD

**Issue by grantbabb** [Open-Network-Insight/open-network-insight#31]
In lda_pre.py (l 36), the file skips a header line.  There is no header line with the current output.

We should also make sure this does not occur in other sections of the script.

**Comment by grantbabb** [comment]
Reviewed the script  and test results.  The skipped line is actually a low impact, but it appears that the word indexes start with "1" instead of "0", this means that the word array at row [0] gets missed, which gives it the zero vector in word_results.csv

Also need to review post_lda.py, it looks like there was a shim that adjusted for a missing row.

**Comment by NathanSegerlind** [comment]
great news... but where is the code for the fix?

**Comment by NathanSegerlind** [comment]
got it from Grant... will open PR w/ his code

**Comment by NathanSegerlind** [comment]
this was merged into 1.0.1
