### ISSUE TITLE
DNS ML reading avro is missing a configuration value.

### ISSUE THREAD

**Issue by rabarona** [Open-Network-Insight/open-network-insight#39]
For reading avro I’ve been changing DPATH value to point to DPATH=${HUSER}/${DSOURCE}/hive/y=${YR}/m=${MH}/d=${DY}/  but for Flow ML to work this path needs to be DPATH=${HUSER}/${DSOURCE}/csv/y=${YR}/m=${MH}/d=${DY}/*.
 
Reading from avro it needs the hive path and no “*” at the end but flows needs to read from csv and “*” at the end.
 
I’ve been thinking on a solution for this like having 2 DPATH variables or replace the hive or csv in ML ops given the flow or dns parameter but I’d like to hear your suggestions.

**Comment by EverLoSa** [comment]
@NathanSegerlind, @grantbabb, can you take a look please.

**Comment by grantbabb** [comment]
I think that the simplest solution is to add a "*" to the scala code for flows -
System.getenv("DPATH")+"*"
It will have the lowest impact later when both data sources point at avro.

**Comment by NathanSegerlind** [comment]
These characters seems to be control sequences for github's markup language...

however, I think Grant's suggestion is the simplest - a simple addition to DPATH with a comment explaining why puts us in the best position for preparing for flows using avro

**Comment by NathanSegerlind** [comment]
doh
talked about it on the phone with Ricardo:

separating the two paths is the way to go... there is no reason why two different inputs should reside at the same exact location

**Comment by grantbabb** [comment]
Aha, I was looking at the end of the string.  Yes, the two config values make sense.
Be sure to update the installation instructions describing the config values.
In 1.1 we should remove the "csv" path.
