### ISSUE TITLE
Replace quantiles Hive script with distributed_quantiles in scala

### ISSUE THREAD

**Issue by grantbabb** [Open-Network-Insight/open-network-insight#4]
When processing internal flows in 1.0, it was faster to calculate the quantile edges in Hive once a week, then have them read in to a file.  We also include some default values in the solution; these quantiles may not be the seem across internal and external flow workloads, but they definitely are not the same across organizations.  Possible ways to remedy this (from good to best):

- Remove default quantiles file and force users to generate their own version
- Run the Hive script as a step in the ml_ops.sh script, which will force the action to occur before it is needed by the rest of the pipeline
- Replace Hive script with the distributed_quantiles function that will be part of 1.1 DNS model.

**Comment by grantbabb** [comment]
fix submitted in oni-ml PR #4

**Comment by natedogs911** [comment]
Open-Network-Insight/oni-ml#4
