### ISSUE TITLE
make MPI command line configurable in the conf files

### ISSUE THREAD

**Issue by NathanSegerlind** [Open-Network-Insight/open-network-insight#44]
The wiki says that we support both IntelMPI and mpich, but the user has to edit the ml_ops.sh file to configure this. 

It would be preferable to limit user configuration edits to the .conf file.  

- make default MPI execution path a setting the config file, providing both command lines for IntelMPI and mpich (by default one could be commented out...)

This way users won't have to edit the ml_ops.sh file when configuring their solution. It would also open up the possibility of letting the MPI execution be toggled at the command line for testing in future versions....

**Comment by natedogs911** [comment]
resolved in Open-Network-Insight/oni-ml#44
