### ISSUE TITLE
Flows - Geoloc error

### ISSUE THREAD

**Issue by LedaLima** [Open-Network-Insight/open-network-insight#46]
Some locations in the iploc.csv file include extra commas in the name, causing this script to crash when trying to read a float value (coordinates) where a text value is stored, after separating the results by commas.

ValueError                                Traceback (most recent call last)
<ipython-input-52-f699fbac3537> in <module>()
----> 1 generate_attack_map_file(anchor_ip, top_inbound_b, outbound, twoway)

<ipython-input-44-1bb9cae0cd64> in generate_attack_map_file(ip, inbound, outbound, twoway)
    396                     'geometry': {
    397                         'type': 'Point',
--> 398                         'coordinates': [float(row[7]), float(row[6])]
    399                     }
    400                 })

ValueError: could not convert string to float: Road Town

**Comment by rabarona** [comment]
Fixed with https://github.com/Open-Network-Insight/oni-oa/issues/44
