### ISSUE TITLE
Remove TOL as config variable in /etc/oni.conf

### ISSUE THREAD

**Issue by grantbabb** [Open-Network-Insight/open-network-insight#5]
It seems to be a common occurrence that the filter tolerance for perimeter, wan, and DNS require different values.  It makes the most sense to add this as a command line parameter and remove it from the default config.

** This issue is only for oni-setup, adding parameter will be part of  different 1.1 issues **

**Comment by natedogs911** [comment]
this is fixed in the reference pull request
Open-Network-Insight/oni-ml#20
