### ISSUE TITLE
missing value in var quantiles (flow pre and post scala)

### ISSUE THREAD

**Issue by grantbabb** [Open-Network-Insight/open-network-insight#56]
there should be a decile for the variable quant, instead there are nine values

in both files the variable should be assigned as such
val quant = Array(**0,0**, 0.1,0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9)

**Comment by NathanSegerlind** [comment]
PR coming

**Comment by natedogs911** [comment]
after discussing with @NathanSegerlind this can be closed.
