### ISSUE TITLE
Need a baseline approach of how to tune tolerance value for machine learning #wiki

### ISSUE THREAD

**Issue by saiganji** [Open-Network-Insight/open-network-insight#73]
I believe that there a need to provide some instructions or approach ONI users of how to tune tolerance value for running 'ml_ops.sh'. 

https://github.com/Open-Network-Insight/oni-ml/blob/1.0.1/ml_ops.sh#L6

**Comment by NathanSegerlind** [comment]
the long term solution might be to sidestep the issue altogether by returning the "top K most anomalous" and leave tweaking the threshold to advanced users...

but I'll something to the wiki

**Comment by saiganji** [comment]
Alright, makes sense. Thank you, @NathanSegerlind
