### ISSUE TITLE
MPI environment variables occasionally get overwritten

### ISSUE THREAD

**Issue by NathanSegerlind** [Open-Network-Insight/open-network-insight#77]
it seems that every now and then, MPI environment variables get overwritten or otherwise undefined

for example,  running mpich 3.13 on our cluster today, I kept seeing:

error while loading shared libraries: libmpi.so.12: cannot open shared object file: No such file or directory

turns our the LD_LIBRARY_PATH had gone undefined, setting it saved the day:

export LD_LIBRARY_PATH=/usr/local/lib

the big issue is:  why did this happen? I had been running MPI on this cluster for a week and so far as I know, nothing really odd had happened there... we should provide defensive steps to prevent such problems

**Comment by natedogs911** [comment]
fixed (or tools provided to fix) on Open-Network-Insight/oni-ml#45
closing
