### ISSUE TITLE
Code standards and unit tests

### ISSUE THREAD

**Issue by enragedginger** [Open-Network-Insight/open-network-insight#83]
Thank you for open sourcing this project and contributing it to the community. It looks like this project has the potential to add a lot of value.

After looking through the source code a bit, I have a few questions. On the surface, this looks to be a fairly complex project given the number of modules. After diving into the individual modules, I'm concerned about the long term maintainability and success of this project. The following things concern me:
- Current lack of unit tests. Adding unit tests will greatly reduce the number of bugs found in the wild on this project and will also enable developers to confidently make contributions to the project without having to worry they've unintentionally broken some hidden feature. Is there a plan to add automated tests?
- "Uber folders" or rather, folders which not only hold every source file for an entire module, but directories which hold source files from a plethora of languages. Is there a plan to reorganize the code into a friendlier, industry standard pattern?
- A rather complicated setup / deploy process. Luckily, there's a lot of documentation on how to get everything set up and running, but given the large number of steps required to spin things up, I'm wondering if there isn't an easier way. Is there a plan to simplify this process?
- Lack of code reusability / adherence to best practices. I'm looking mostly at the oni-ml Scala files, as I'm more comfortable with Scala than the other languages used in this project. After paging through these, it becomes apparent that they're meant for running inside of a Spark shell. But I'm left with other questions such as:
  - Why aren't there any comments? With neither comments nor tests how am I supposed to know what this code does / should be doing? Are there plans to add comments and tests?
  - Why do methods like `toDouble` and `isNumeric` appear in multiple files? I merely use these as a basic example. In general, why not pull common, re-usable code out into a library?
  - Why are large chunks of code commented out? Will they be useful in the future? If so, when? If not, why not remove them as source control tracks our changes and we can always go back and grab them if we need them.
  - Why aren't standard Scala patterns / features (such as case classes, pattern matching, using Option to wrap possible null / empty values, etc.) in use? Is there a plan to switch to idiomatic Scala?

This sounds like a lot of work, but given the amount of work that's been put into the project up to this point coupled with the potential value-add of this project, I'd like to see it succeed just as much as the next guy.

I look forward to hearing back from you.

-Stephen

**Comment by NathanSegerlind** [comment]
We whole heartedly concur with you on all points regarding the 1.0.1 branch.

Upcoming 1.1 release (in current dev branches) will address many of these issues, in particular: Creation of unit tests and unit test framework, removal of "uber folders" for a standard src hierarchy structure, real comments, no more commented out code, better use of Scala, etc.

**Comment by natedogs911** [comment]
First thank you for your interest in the project and recognizing the value,
We are glad to have your feedback.

As @NathanSegerlind  already stated most of the concerns noted will be greatly improved if not solved with the improvements in 1.1, which will be released very shortly.

* Current lack of unit tests
* Uber Folders
* Lack of code reusability
* other bug fixes and enhancements

Items we are aware of and continue to work on,

* Improved setup and deployment options
* Repo structure / multiple repo's
* Documentation improvements

I look forward to further feedback.

Regards,

Nathanael

**Comment by enragedginger** [comment]
Thanks for the quick response. I now see the changes you're referring to.

Coming into the project, I was a bit confused as the branch defaulted to master and no changes had been made to that branch for a month, but the only other branch seemed less relevant. I now see that the extra branches exist within the individual submodules. Is there a reason for using Git submodules here instead of just partitioning everything into folders like the Apache Hadoop, Spark, or Kudu projects are doing? Secondly, can we either (a) make "dev" the Git "default" branch for these repositories or (b) add something to the README.md in the root of each project indicating that master might be substantially behind the other branches? I think this will make it easier for developers to familiarize themselves with the project and start making contributions.

Anyhow, I'll start looking at the dev branches now.

Thank you!

**Comment by natedogs911** [comment]
current spot branch in the main repo Open-Network-Insight/open-network-insight reflects a standard repo structure. we will continue to work on the docs and also once we move to the Apache Spot Git the branches will be more standardized.

**Comment by enragedginger** [comment]
Thank you!
