### ISSUE TITLE
Installation and Usages

### ISSUE THREAD

**Issue by kallolkk** [Open-Network-Insight/open-network-insight#85]
Hi,
I'm new to cloudera. My work is mostly network security related. I want to try Open Network Insight. Is there any proper video /document for installation and for usages. Please provide me the link. Thanking you all.

Best regards
Kallol

**Comment by EverLoSa** [comment]
Hi @kallolkk you can find our wiki in the following link: https://github.com/Open-Network-Insight/open-network-insight/wiki

The current version is 1.0.1, but we are releasing  1.1 soon with significant changes. Currently you can look in our “dev” branch to get started with the new version

oni-ingest
https://github.com/Open-Network-Insight/oni-ingest/tree/dev

oni-ml
https://github.com/Open-Network-Insight/oni-ml/tree/dev

oni-oa
https://github.com/Open-Network-Insight/oni-oa/tree/dev

**Comment by cberho** [comment]
Hey! @kallolkk your counterpart on the project here lol xD
 Once you moved on with the setup, we can have a walk through and brief you on functionality for the current telemetry sources.

**Comment by kallolkk** [comment]
Hi 
Thanks guys. I'm confused about the deployment portion. Do I need to create a VM network and go with the hybrid deployment option (Option 2).  For me creating a VM network will be a problem, mainly RAM, mine is limited to 32 GB. If I download a single Cloudera Hadoop Dist. VM and install ONI-ingest, oni-ml, oni-oa. Will ONI work like that way ? Also, is it only for real time network data ?  If some one wants to analyze off-line network capture (pcap files), will it work?
Thanks in advance.
Regards
Kallol

**Comment by natedogs911** [comment]
Hello @kallolkk 

I don't see a reason why you should not be able to run the whole solution in one VM,
however you will need to keep in mind that the amount of data you could potentially process in the VM will be much smaller then running in a normal cluster environment.

Processing offline data should not be a problem, you simply need to load the files in the collector_path.

If you want to share more about how you are trying to process the data we will be happy to help you,

Regards

**Comment by natedogs911** [comment]
closing for now, please re-open if more help is needed @kallolkk

**Comment by kallolkk** [comment]
Hi All,
Just going over the setup process. Sorry for the late, over ran by other issues.  I'm stack again.
Process I did:
step1: cloned the git (git clone  https://github.com/Open-Network-Insight/oni-setup.git)
step2: configured the conf file. my file:
#node configuration
NODES=('node-01')
UINODE='node01'
MLNODE='node01'
GWNODE='node01'
DBNAME='cloudera'

#hdfs - base user and data source config
HUSER='/user/cloudera'
DSOURCES='flow'
DFOLDERS=('binary' 'csv' 'hive' 'stage')
DNS_PATH=${HUSER}/${DSOURCE}/hive/y=${YR}/m=${MH}/d=${DY}/
PROXY_PATH=${HUSER}/${DSOURCE}/hive/y=${YR}/m=${MH}/d=${DY}/
FLOW_PATH=${HUSER}/${DSOURCE}/hive/y=${YR}/m=${MH}/d=${DY}/
HPATH=${HUSER}/${DSOURCE}/scored_results/${FDATE}

#impala config
IMPALA_DEM='node01'

KRB_AUTH=false
KINITPATH=
KINITOPTS=
KEYTABPATH=
KRB_USER=

#local fs base user and data source config
LUSER='/home/cloudera'
LPATH=${LUSER}/ml/${DSOURCE}/${FDATE}
RPATH=${LUSER}/ipython/user/${FDATE}
LDAPATH=${LUSER}/ml/oni-lda-c
LIPATH=${LUSER}/ingest

SPK_EXEC='400'
SPK_EXEC_MEM='2048m'
SPK_DRIVER_MEM=''
SPK_DRIVER_MAX_RESULTS=''
SPK_EXEC_CORES=''
SPK_DRIVER_MEM_OVERHEAD=''
SPAK_EXEC_MEM_OVERHEAD=''
TOL='1e-6'


# MPI configuration

# command to run MPI
MPI_CMD='mpiexec'

# command to prepare system for MPI, eg. load environment variables
MPI_PREP_CMD=''

# number of processes to run in MPI
PROCESS_COUNT=20
step3: copied it in /etc/ folder.
step4: changed the conf file name in hdfs_setup.sh to match mine in etc folder.
step5: run the hdfs_setup.sh  script.
Errors: 
[error.txt](https://github.com/Open-Network-Insight/open-network-insight/files/565618/error.txt)
 
I'm using cloudera startup VM, with 4 cpu core and 14gb of ram. I didn't created any new user, instead of that i'm using cloudera default user.  Not sure what I'm doing wrong.
Thanks .

Kallol

**Comment by natedogs911** [comment]
Hello @kallolkk, it seems these are all connection related.
it would seem that the basic hadoop commands are not working,
for instance the script is trying `sudo -u hdfs hadoop fs -mkdir ${HUSER}`
$HUSER would be `cloudera` in your case.

can you try both of these commands from your terminal and let me know what happens?
`sudo -u hdfs hadoop fs -mkdir cloudera`
and
`hadoop fs -mkdir cloudera`

**Comment by kallolkk** [comment]
Hi,
just followed your instructions, and you are right hadoop is not responding. But I cant understand since its the cloudera startup VM, by default hadoop should work. Or am I missing something. Posting the terminal response below:
[cloudera@quickstart oni-setup]$ sudo -u hdfs hadoop fs -mkdir cloudera
mkdir: Call From quickstart.cloudera/127.0.0.1 to quickstart.cloudera:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
[cloudera@quickstart oni-setup]$ hadoop fs -mkdir cloudera
mkdir: Call From quickstart.cloudera/127.0.0.1 to quickstart.cloudera:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
[cloudera@quickstart oni-setup]$ 

Thanks

**Comment by kallolkk** [comment]
Hi,
I'm able to turn on hadoop in cloudera system. It worked ok for the first phase, still i have got some warnings. terminal response:
[cloudera@quickstart oni-setup]$ ./hdfs_setup.sh 
mkdir: `/user/cloudera': File exists
creating /flow
creating flow/binary
creating flow/csv
creating flow/hive
creating flow/stage
creating /dns
creating dns/binary
creating dns/csv
creating dns/hive
creating dns/stage
creating /proxy
creating proxy/binary
creating proxy/csv
creating proxy/hive
creating proxy/stage
16/11/02 22:52:31 WARN mapreduce.TableMapReduceUtil: The hbase-prefix-tree module jar containing PrefixTreeCodec is not present.  Continuing without it.

Logging initialized using configuration in jar:file:/usr/lib/hive/lib/hive-common-1.1.0-cdh5.8.0.jar!/hive-log4j.properties
OK
Time taken: 1.688 seconds
16/11/02 22:52:39 WARN mapreduce.TableMapReduceUtil: The hbase-prefix-tree module jar containing PrefixTreeCodec is not present.  Continuing without it.

Logging initialized using configuration in jar:file:/usr/lib/hive/lib/hive-common-1.1.0-cdh5.8.0.jar!/hive-log4j.properties
hiveconf:huser=/user/cloudera
hiveconf:dbname=cloudera
OK
Time taken: 1.879 seconds
16/11/02 22:52:47 WARN mapreduce.TableMapReduceUtil: The hbase-prefix-tree module jar containing PrefixTreeCodec is not present.  Continuing without it.

Logging initialized using configuration in jar:file:/usr/lib/hive/lib/hive-common-1.1.0-cdh5.8.0.jar!/hive-log4j.properties
hiveconf:huser=/user/cloudera
hiveconf:dbname=cloudera
OK
Time taken: 1.752 seconds
16/11/02 22:52:55 WARN mapreduce.TableMapReduceUtil: The hbase-prefix-tree module jar containing PrefixTreeCodec is not present.  Continuing without it.

Logging initialized using configuration in jar:file:/usr/lib/hive/lib/hive-common-1.1.0-cdh5.8.0.jar!/hive-log4j.properties
hiveconf:huser=/user/cloudera
hiveconf:dbname=cloudera
OK
Time taken: 0.694 seconds
[cloudera@quickstart oni-setup]$ 

Thanks
