### ISSUE TITLE
Inconsistent/incorrect use of Apache trademark

### ISSUE THREAD

**Issue by mikeridley** [Open-Network-Insight/open-network-insight#88]
In some cases, the project's web site is using the language Apache Spot instead of Apache Spot (incubating).  There seems to have been some kind of global search and replace, as a blog post from March 29, 2016 (http://open-network-insight.org/open-network-insight-3-most-asked-questions/) refers to Apache Spot, when no such term existed at that time (and it should be Apache Spot (incubating) even now).

**Comment by natedogs911** [comment]
Thank you, we are working on this.

**Comment by natedogs911** [comment]
@mikeridley the noted site has been updated, Also the below needs to be updated but is in the works:

http://open-network-insight.org/jupyter-notebooks-for-data-analysis/
http://spot.incubator.apache.org/jupyter-notebooks-for-data-analysis/
