### ISSUE TITLE
Wiki page and content issues

### ISSUE THREAD

**Issue by JonZeolla** [Open-Network-Insight/open-network-insight#94]
The wiki seems to have a couple of issues.  

1. On the [Apache Spot (incubating) overview page](https://github.com/Open-Network-Insight/open-network-insight/wiki/Overview%20of%20Apache%20Spot%20%20(Incubating)) there is duplication of text - from the second 'The Business of Network Security – The “Port Perspective"' to the word 'Spot'.  
1. The [Technical Overview](https://github.com/Open-Network-Insight/open-network-insight/wiki/Technical%20Overview) page doesn't seem to exist or is broken.

**Comment by natedogs911** [comment]
the technical overview is now here:
https://github.com/Open-Network-Insight/open-network-insight/wiki/Apache-Spot-Technical-Overview

both issues are now fixed, thanks @EverLoSa
