### ISSUE TITLE
README updates

### ISSUE THREAD

**Issue by JonZeolla** [Open-Network-Insight/open-network-insight#95]
Some READMEs could use updates.  

1. The [main README](https://github.com/Open-Network-Insight/open-network-insight/blob/master/README.md) has a typo of "contribuitions".
1. The [spot-ingest README](https://github.com/Open-Network-Insight/open-network-insight/blob/spot/spot-ingest/README.md) should probably use the picture from [here](https://github.com/Open-Network-Insight/open-network-insight/blob/spot/spot-ingest/ONI_Ingest_Framework1_1.png), not [here](https://github.com/Open-Network-Insight/open-network-insight/blob/spot/spot-ingest/docs/ONI_Ingest_Framework1_1.png).
1. The components README context link should be either [this](https://github.com/Open-Network-Insight/oni-oa/tree/1.1/context/README.md) or [this](https://github.com/Open-Network-Insight/oni-oa/tree/master/context/README.md), as it is currently [broken](https://github.com/Open-Network-Insight/oni-oa/blob/1.1/oa/context/README.md).

I know things are in a bit of flux with the move to Apache Spot (incubating), but I was just reading through some documentation pre-migration and found these items.  Happy to take another look once things are migrated and fix them myself with a PR once I don't need to sign something to do so.  =)

**Comment by natedogs911** [comment]
taking a look @JonZeolla

**Comment by natedogs911** [comment]
i believe all of the above have been fixed in the spot branch of the main repo (Open-Network-Insight/open-network-insight) which will be the code/docs transitioning to the Apache Spot git repo.

closing for now, let me know if something was missed
